name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
          
      # Verify project structure
      - name: Verify project structure
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Contents of installer/client directory (if exists):"
          ls -la ./installer/client || true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          if [ -f "./installer/client/package-lock.json" ]; then
            npm ci
          else
            npm install
          fi
        working-directory: ./installer/client

      # ✅ Auto-fix lint/prettier issues
      - name: Lint and fix code
        run: npm run lint -- --fix || true
        working-directory: ./installer/client
      
      - name: Build application
        run: npm run build
        working-directory: ./installer/client
        env:
          NODE_ENV: production
          
      - name: Verify build output
        run: |
          echo "Checking build output..."
          if [ -d "./installer/client/dist" ]; then
            echo "✅ Found dist folder"
            ls -la ./installer/client/dist
          elif [ -d "./installer/client/build" ]; then
            echo "✅ Found build folder"
            ls -la ./installer/client/build
          else
            echo "❌ No build output found"
            exit 1
          fi

      - name: Deploy to Azure Static Web Apps
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN  }}
          action: "upload"
          app_location: "./installer/client"
          api_location: ""
          output_location: "dist" # or "build" depending on your Vue setup
          skip_deploy_on_missing_secrets: true
        env:
          NODE_ENV: production

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"



